#!/bin/sh

NAME="aesdsocket"
DAEMON="/usr/bin/$NAME"

case "$1" in
    start)
        echo "Starting $NAME..."
        start-stop-daemon -S -n "$NAME" -a "$DAEMON" -- -d
        ;;

    stop)
        echo "Stopping $NAME..."
        start-stop-daemon -K -n "$NAME" --signal TERM
        ;;

    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
